server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:api-gateway}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTHENTICATION-SERVICE          # service ID is stable; keep literal
          predicates:
            - Path=/auth/**,/users/**
          filters:
            - StripPrefix=1

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**
          filters:
            - StripPrefix=1

        - id: rtc-service
          uri: ${RTC_WS_URI:lb:ws://REAL-TIME-COMMUNICATION}  # websocket route; env overrideable
          predicates:
            - Path=/rtc/**,/ws/**
          filters:
            - StripPrefix=1

        - id: todo-service
          uri: lb://TO-DO-LIST-SERVICE
          predicates:
            - Path=/todo/**,/lists/**,/catalog/**
          filters:
            - StripPrefix=1

      default-filters:
        - RemoveHopByHop=connection,keep-alive,transfer-encoding,te,trailer,proxy-authorization,proxy-authenticate,upgrade
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

      httpclient:
        connect-timeout: ${GATEWAY_CONNECT_TIMEOUT_MS:5000}
        response-timeout: ${GATEWAY_RESPONSE_TIMEOUT:10s}

      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
            allowedMethods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,PATCH,DELETE,OPTIONS}
            allowedHeaders: ${CORS_ALLOWED_HEADERS:*}
            exposedHeaders: ${CORS_EXPOSED_HEADERS:Authorization,Content-Type}
            allowCredentials: ${CORS_ALLOW_CREDENTIALS:true}
            maxAge: ${CORS_MAX_AGE:3600}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_JWKS_URI:http://auth-service:8092/.well-known/jwks.json}
          issuer-uri: ${JWT_ISSUER:http://auth-service:8092}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://service-registry:8761/eureka/}
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA:true}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY:true}
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info,prometheus}

rate:
  limit:
    requests: 60
    window-seconds: 60